spring:
  kafka:
    bootstrap-servers: pkc-z9doz.eu-west-1.aws.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='YJFXZRHURBWGEESL' password='tbYllbDe4Cc4Whn5ypRA39QcseFQxmvxOMShGktBISp3osjg3YUycS4eCUvv5ecZ';
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer